require("plugins")
require("config")

-- plugins
-- vim.pack.add({
-- 	'https://github.com/chentoast/marks.nvim',
--
-- 	'https://github.com/nvimtools/none-ls.nvim',
-- 	'https://github.com/jay-babu/mason-null-ls.nvim',
-- })

-- require('marks').setup({
-- 	builtin_marks = { '<', '>', '^' },
-- })
--
--
-- -- treesitter
-- require('nvim-treesitter.configs').setup({
-- 	ensure_installed = {
-- 		'lua', 'php', 'javascript', 'typescript', 'markdown', 'sql', 'c'
-- 	},
-- 	highlight = { enabled = true },
-- 	indent = { enabled = true },
-- })
--
-- vim.filetype.add({
-- 	extension = {
-- 		inc = 'php',
-- 	},
-- })
--
-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = { "php", "inc", "sql" },
-- 	callback = function()
-- 		vim.opt_local.expandtab = true
-- 	end,
-- })
--
-- -- mason
-- require('mason').setup()
-- require('mason-lspconfig').setup({
-- 	ensure_installed = {
-- 		'intelephense', 'eslint', 'ts_ls'
-- 	},
-- })
--
-- require('mason-null-ls').setup({
-- 	ensure_installed = {
-- 		'php-cs-fixer', 'prettier', 'eslint_d', 'phpcs'
-- 	}
-- })
--
--
-- -- lspconfig
-- vim.lsp.start({
-- 	name = 'intelephense',
-- 	cmd = { 'intelephense', '--stdio' },
-- 	root_dir = vim.fs.root(0, { 'composer.json', '.git' }),
-- 	on_attach = function(client, buffer)
-- 		local opts = { buffer = bufnr, silent = true }
-- 		map("n", "gd",         vim.lsp.buf.definition, opts)
--         map("n", "K",          vim.lsp.buf.hover, opts)
--         map("n", "gr",         vim.lsp.buf.references, opts)
--         map("n", "<leader>rn", vim.lsp.buf.rename, opts)
-- 	end,
-- 	capabilities = require('cmp_nvim_lsp').default_capabilities(),
-- })
